# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohgovIVd5HJoCLwpx6BRzhmh27L-tqGJ
"""

import yfinance as yf
import pandas as pd

def get_stock_data(symbol):
    """
    Downloads stock data from Yahoo Finance and returns adjusted closing prices if available.
    Falls back to 'Close' prices if 'Adj Close' is missing.
    """
    data = yf.download(symbol, progress=False)

    print("Available columns:", data.columns)

    if 'Adj Close' in data.columns:
        return data['Adj Close']
    elif 'Close' in data.columns:
        return data['Close']
    else:
        raise ValueError("Neither 'Adj Close' nor 'Close' found in the data.")

def calculate_returns(price_series):
    """
    Computes daily percentage returns from a pandas Series of prices.
    """
    returns = price_series.pct_change().dropna()
    return returns

if __name__ == "__main__":
    symbol = "GS"
    try:
        prices = get_stock_data(symbol)
        print("\nStock Prices (Last 5 rows):\n", prices.tail())

        returns = calculate_returns(prices)
        print("\nStock Returns (Last 5 rows):\n", returns.tail())

    except Exception as e:
        print("Error fetching data:", e)