# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohgovIVd5HJoCLwpx6BRzhmh27L-tqGJ
"""

# Identify yourself for grading

def WhoAmI():
    return('yl5862')